### ISSUE TITLE
ImportError: No module named 'board'

### ISSUE THREAD

**Issue by julian-labuschagne** [sarumont/py-trello#105]
Hi there,

I have installed with: 

> sudo pip install py-trello

I can see the files was installed to:

> /usr/local/lib/python3.4/dist-packages/trello

There is a file called:

> /usr/local/lib/python3.4/dist-packages/trello/board.py

But each time I run my script I get the following error:

>Traceback (most recent call last):
>  File "myscript.py", line 5, in <module>
>    from trello import TrelloClient
>  File "/usr/local/lib/python3.4/dist-packages/trello/__init__.py", line 2, in <module>
>    from board import *
>ImportError: No module named 'board'

**Comment by nMustaki** [comment]
Hi,
I screw up my previous PR, but I submitted a new one to @sarumont which will fix it. Sorry...

**Comment by sarumont** [comment]
@julian-labuschagne I merged @nMustaki's fix and push an update. Try `0.4.1` which is available now in pypi.

**Comment by julian-labuschagne** [comment]
@sarumont @nMustaki Thanks I upgraded to 0.4.1 and everything is working as expected now.
