### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aviaryan** [sarumont/py-trello#112]
Is there some kind of documentation for the package ? I find it very hard to get started with it.

**Comment by sarumont** [comment]
There is the main `README`, and there is documentation in the code itself. There are also unit tests which utilize the library.

Outside of that, there is no Real Documentation (tm) as of now.

**Comment by berezovskyi** [comment]
http://py-trello.readthedocs.io/en/latest/ but needs a fair amount of love.

**Comment by sarumont** [comment]
@JoshMayberry Unless it comes from the community, it's probably not going to happen. :)
