### ISSUE TITLE
How to post and retrieve comment card data through Trello API?

### ISSUE THREAD

**Issue by TonyEight** [sarumont/py-trello#113]
[StackOverflow Original Post](http://stackoverflow.com/questions/33320353/how-to-post-and-retrieve-comment-card-data-through-trello-api)

I'm building a web app that pushes and pulls data to/from Trello using its API.

The current stack is pythonic and I use [py-trello](https://github.com/sarumont/py-trello) to manage most of the API calls.
But there's one endpoint leaving me perplex : [post a comment on a card](https://developers.trello.com/advanced-reference/card#post-1-cards-card-id-or-shortlink-actions-comments)

It seems like the current [py-trello](https://github.com/sarumont/py-trello) implementation does not provide a way to post a new comment and immediately retrieve its data. For example, you can do it with a List :

    def add_list(self, name):
        """Add a list to this board
        :name: name for the list
        :return: the list
        :rtype: List
        """
        obj = self.client.fetch_json(
            '/lists',
            http_method='POST',
            post_args={'name': name, 'idBoard': self.id}, )
        return List.from_json(board=self, json_obj=obj)

Trello API return the created list object as a JSON object. [py-trello](https://github.com/sarumont/py-trello) turns this JSON into a [List](https://github.com/sarumont/py-trello/blob/master/trello/trellolist.py) object.

Is there a way to do the same with [Card](https://github.com/sarumont/py-trello/blob/master/trello/card.py) comment? Card class comes with an *"add comment"* feature ([code](https://github.com/sarumont/py-trello/blob/master/trello/card.py#L298)).

But Trello seems to return nothing...

    >>> # Card definition
    >>> card = Card(parent=trello_board, card_id=id)
    >>> # Fetching card data
    >>> card.fetch()
    >>> # This is correctly pushed to Trello
    >>> obj = card.comment('Foo, bar!')
    >>> import pprint
    >>> # Hoping to print a big fat JSON
    >>> pp = pprint.PrettyPrinter(indent=4)
    >>> pp.pprint(obj)
    None

Any clue ? Thanks alot !

**Comment by TonyEight** [comment]
Hi, again.

I might have found my solution. The issue, if we can call that an issue, was that the `Card.comment()` method was not return anything. So I came up with two ways to solve this.

## The quick one

*This is the one I used to get quick results.*

In my usage of **py-trello**, I built some sort of backend that handles my calls to the Trello API using **py-trello**.

    # path/to/trello_backend/definition.py
    from trello import TrelloClient
    from trello_backend.models import TrelloConfiguration
    
    class Backend(object):
        trello_config = TrelloConfiguration.get_solo()
        new_tickets_list = None

        def __init__(self, clear_board=False, clear_lists=False):
            self.client = self._get_trello_client()
            self.board = self._get_trello_board()
            if clear_board:
                self.clear_trello_board_config()
            # ...more unrelevant code
            self.init_trello_lists_config()

        def _get_trello_client(self):
            return TrelloClient(
                api_key = self.trello_config.trello_api_key, 
                api_secret = self.trello_config.trello_api_secret, 
                token = self.trello_config.trello_user_token, 
                token_secret = self.trello_config.trello_user_token_secret
            )

        def _get_trello_board(self):
            pass

So I just added a new method to my `Backend` object.

    class Backend(object):
        # ...unrelevant code
        def add_comment(self, card_id, text):
            return self.client.fetch_json(
                '/cards/' + card_id + '/actions/comments',
                http_method='POST',
                post_args={'text': text}
            )
        # ...more unrelevant code

So I can catch the Trello API return after the new comment's been posted. And use it as I want. Could also *JSON-parse* it and turn it into another object.

## The other one : longer maybe

*I might submit it as a feature request or directly a pull-request.*

It consists in implementing a new `Comment` object into **py-trello** such as `List` or `Card`. Then rewrite the [`Card.comment()`](https://github.com/sarumont/py-trello/blob/master/trello/card.py#L298) method so that it can work just as the [`List.add_card()`](https://github.com/sarumont/py-trello/blob/master/trello/trellolist.py#L48) method which returns a `Card` object (the new one that has just been added).

Thank you anyway !

**Comment by AkaYasmine** [comment]
aaaaaa
