### ISSUE TITLE
Meaningless .encode('utf-8').decode('utf-8') ?

### ISSUE THREAD

**Issue by JulienPalard** [sarumont/py-trello#118]
In this commit https://github.com/sarumont/py-trello/commit/11945eaf9380654ffe7ae545fc239445e0745836 I don't understand why you're decoding what you're encoding, that's meaningless.

The only "side effect" I can see of doing this is to raise an exception when the string is not UTF-8 in the first place (can it be possible ?), yet that's a particularly unreadable way to express "I'm checking for UTF-8 compliance".

Also, I tried to run `test/test_board.py` (to test with python3 -bb) but your tests won't even start:
```
======================================================================
ERROR: setUpClass (__main__.TrelloBoardTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_board.py", line 24, in setUpClass
    if not cls._board:
AttributeError: type object 'TrelloBoardTestCase' has no attribute '_board'

----------------------------------------------------------------------
Ran 0 tests in 0.300s
```

**Comment by sarumont** [comment]
@JulienPalard Thanks for catching this - I meant to close, not merge that PR. I've reverted it in `master`.

For the error you're seeing, have you set the environment variable `TRELLO_TEST_BOARD_NAME` to a valid board on your account? This is how the test suite is determining what board to use for dropping test data onto.

**Comment by JulienPalard** [comment]
I don't remember that, sry :-P If this was my error, please raise something more verbose for the next time i'll try them ;-)
