### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by TooAngel** [sarumont/py-trello#134]
Hey, I want to kindly ask if there are plans for the next release?

I would like to see especially https://github.com/sarumont/py-trello/commit/33404517a08a3090a503a91ae00429ce1860e766 be in the released version.

Can I somehow help to get the next release out?

**Comment by sarumont** [comment]
Hi! I just deployed `0.5.0` to PyPi. Cheers!

**Comment by TooAngel** [comment]
Perfect, thx
