### ISSUE TITLE
Unicode handling

### ISSUE THREAD

**Issue by brutasse** [sarumont/py-trello#135]
In various places py-trello `.encode('utf-8')` some strings returned by the API.

What's the rationale behind this? Trello data is returned in JSON, with string keys and attributes in unicode strings (`u'foo'` in Python 2, `'foo'` in Python 3).

Keeping unicode would make sense: in Python 2 you can compare bytestrings to unicode strings implicitly (`u'foo' == 'foo'`), but in Python 3 it'd make more sense to compare e.g. `board.name` to unicode strings instead of bytestrings. In Python 3 our code needs to re-decode data for comparison or string formatting. We have things like:

`if board.name == b'Board name'`

or:

`message = '{}: {}'.format(board.name.decode(), card.name.decode())`

My suggested fix would be to remove [all occurrences](https://github.com/sarumont/py-trello/search?utf8=%E2%9C%93&q=encode) of `.encode('utf-8')` here, to have a proper [unicode sandwich](http://nedbatchelder.com/text/unipain/unipain.html#35) behavior. Any objections? I'm happy to submit a PR.

**Comment by brutasse** [comment]
Refs #66 #118

**Comment by sfriesel** [comment]
this is the first commit that introduced the encoding: https://github.com/sarumont/py-trello/commit/c925101d017d02d38b922c5362ad57cb4cefeb2e which was triggered by a wrong implementation of `repr` in the previous commit https://github.com/sarumont/py-trello/commit/29141189b912c49f372c608f5d60b79ce0a20c35

**Comment by sarumont** [comment]
No objections to proper UTF-8 fixes. I merged the previous PR, as I didn't have the time to properly review it. :) PRs are welcome!

**Comment by sfriesel** [comment]
choose your poison :)

**Comment by sarumont** [comment]
Thanks for the work, guys! I merged #138, and I bumped the version to `0.6.0`. Anyone who is depending on the old, broken behavior can still use `0.5.1`. #139 appears to have been a subset of #138, so I won't worry about that unless I missed something @sfriesel.

**Comment by brutasse** [comment]
Thanks for the merge, @sarumont!
