### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by Signum** [sarumont/py-trello#14]
I'm missing any documentation. The tests gave me a hint but docstrings or a brief API documentation would really help.

**Comment by xguse** [comment]
update on this...?  Not really providing the atmosphere of a project that wants folks to actually us it without them.

**Comment by WoLpH** [comment]
I've added docs last week: http://py-trello.readthedocs.org/en/latest/

**Comment by WoLpH** [comment]
This ticket should be closed btw, has been fixed by #88

**Comment by sarumont** [comment]
Thanks, @WoLpH. I'll close this since #88 gets a lot of the way there. More documentation PRs are always welcome. :)
