### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by NiFNi** [sarumont/py-trello#146]
Error:

> File "/usr/local/lib/python3.4/dist-packages/trello/compat.py", line 13, in force_str
>     if PY2 and isinstance(s, unicode):  # noqa
> NameError: name 'unicode' is not defined

when calling list_boards() on a TrelloClient instance.

Works fine in version 0.5.0 but breaks in 0.6.0.

Python version: 3.4.3
sys.version_info returns:
> sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)

**Comment by 211217613** [comment]
Quick SO search shows that the project has been developed in python2. You (and me) are trying to run it in Python3, where there is no ```unicode``` name.
reference: http://stackoverflow.com/questions/36110598/nameerror-name-unicode-is-not-defined

I'm going to either abandon py-trello or try running in python2

**Comment by 211217613** [comment]
Just confirmed it...use it with python2 and all is well.

**Comment by NiFNi** [comment]
Well they check if it's python 2 and if not the part with the Unicode would not be executed.. But somehow they broke this check in version 0.6.0 as everything is fine in version 0.5.0.. Even with python 3

**Comment by sarumont** [comment]
Hey, guys. I believe #144 should have fixed this for Python 3. I'll publish a patch version to pypi with that commit this week.

**Comment by NiFNi** [comment]
Hey,
@sarumont it is not realeased yet is it?
Would be great if you can mention me here when it is done so I can close the issue and upgrade to the newer version.

**Comment by sarumont** [comment]
@NiFNi I just published it to pypi - Let me know if `0.6.1` works for you!

**Comment by NiFNi** [comment]
@sarumont working fine now! Thank you for the quick reply and keep up the good work :+1:
