### ISSUE TITLE
Extracting string data from cards

### ISSUE THREAD

**Issue by 211217613** [sarumont/py-trello#148]
I can pull down lists and cards and card data, specifically strings, from the api but the `get_cards()` class member returns a Card class type. How can I use something like `card.split()` with the return type.

I just want to parse a '-' delimited string.

**Comment by sarumont** [comment]
The `py-trello` library provides bindings to Trello objects, so fetching stringified versions of these objects are not supported. This is a more raw operation and can easily be accomplished with a basic REST library.
