### ISSUE TITLE
No Way to Update Board Name

### ISSUE THREAD

**Issue by bculpepper** [sarumont/py-trello#168]
Forgive me if I am missing something but, from what I can tell, there is no way to update a board name. I can,

get the board with:
my_board = client.get_board(board_id='someBoardId')

update the name with:
my_board.name = "New Board Name"

But the save function is doing a POST rather than a PUT so the new name is not saved.
my_board.save()

Shouldn't this functionality exist?
https://developers.trello.com/advanced-reference/board#put-1-boards-board-id-name

Please let me know if I am just missing something.

Thanks!

Brandon Culpepper

**Comment by sgaynetdinov** [comment]
Hello, you're right method `Board.save()` does not change the name.
I tried to use a `PUT`, and the `board name` has changed.

Add new method
https://github.com/sarumont/py-trello/pull/169

**Comment by bculpepper** [comment]
Nice work @sgaynetdinov . I was actually going to do the very same pull request if I had not heard back from anyone today.

Thanks!

**Comment by sgaynetdinov** [comment]
@bculpepper master merge pull requests #169

**Comment by bculpepper** [comment]
Thanks @sgaynetdinov! Works perfectly. Will the update be out on pip soon? I am having a hard time getting Heroku to pick up the changes even when using -e and the github url in the requirements.txt file.

**Comment by sarumont** [comment]
Yeah, I'll try to publish a new version this week. Thanks for the contribs!

**Comment by sarumont** [comment]
`0.7.0` uploaded to PyPi!
