### ISSUE TITLE
NameError: name 'Board' is not defined

### ISSUE THREAD

**Issue by jcchristian** [sarumont/py-trello#186]
I'm trying to get all boards from my organization, but end up getting `NameError: name 'Board' is not defined`.

	orgs = trello.list_organizations()
	my_org = None
	for org in orgs:
		if org.name == "my_cool_org":
			my_org = org

	print(my_org.all_boards())

Traceback:

```
Traceback (most recent call last):
  File "D:/.../main.py", line 37, in <module>
    print(my_org.all_boards())
  File "D:\...\lib\site-packages\trello\organization.py", line 47, in all_boards
    return self.get_boards('all')
  File "D:\...\lib\site-packages\trello\organization.py", line 58, in get_boards
    return [Board.from_json(organization=self, json_obj=obj) for obj in json_obj]
  File "D:\...\lib\site-packages\trello\organization.py", line 58, in <listcomp>
    return [Board.from_json(organization=self, json_obj=obj) for obj in json_obj]
NameError: name 'Board' is not defined
```

Using py-trello 0.8.0 from pypi (https://pypi.python.org/pypi/py-trello/0.8.0)

**Comment by sgaynetdinov** [comment]
Hello, this bug close in https://github.com/sarumont/py-trello/issues/172
was not update in pip, use https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

**Comment by sgaynetdinov** [comment]
@jcchristian @sarumont 
This error is fixed, can we close?

**Comment by jcchristian** [comment]
Yup.
