### ISSUE TITLE
Label comparison not working

### ISSUE THREAD

**Issue by jcchristian** [sarumont/py-trello#187]
I created a dict that consists of all my board labels, key being the label name and value being the Label object, as follows: `{'TO DO': <Label TO DO>, 'DONE': <Label DONE>, 'VERIFIED': <Label VERIFIED>, 'APPROVED': <Label APPROVED>, 'DOING': <Label DOING>}`

I'm working on a personal script to automate some Trello related jobs, one of them is keeping card labels up-to-date based on some rules and external sources. Let's say I have the card _LoremIpsum_ with only one label, `<Label TO DO>`.

If I try to do this:

```
board_labels = {label.name: label for label in card.board.get_labels()}  # board_labels: {'TO DO': <Label TO DO>, 'DONE': <Label DONE>, 'VERIFIED': <Label VERIFIED>, 'APPROVED': <Label APPROVED>, 'DOING': <Label DOING>}
print(card.labels)  # print: [<Label TO DO>]
print(board_labels["TO DO"] in card.labels)  # print: False
```

It should print **True**, but instead it print **False**, why?

**Comment by jcchristian** [comment]
Any update? 6 days old ticket :(

**Comment by jcchristian** [comment]
So, just checked inside `label.py` and it's simply because there isn't an override of `__eq__`, something like:

	def __eq__(self, other):
		return self.id == other.id if isinstance(other, self) else False

Would do the trick :)

**Comment by sgaynetdinov** [comment]
Hello, i'm create pull request (https://github.com/sarumont/py-trello/pull/193)
which closes the problem with `Label`

> PS: The same could and should be done for card, board, etc, as comparing objects like these is pretty common :)
You can create dressed tasks for these questions?

**Comment by jcchristian** [comment]
@sgaynetdinov I'll try to do that on my spare time.
