### ISSUE TITLE
Maintain PyPi py-trello up-to-date

### ISSUE THREAD

**Issue by juanchristian** [sarumont/py-trello#203]
When we talk about Python, one of the first things that comes to mind is PyPi, the great packages repository. This Trello wrapper is amazing but it's always outdated on PyPi vs here on Github. It would be amazing if the contributors could maintain both platforms up-to-date and aligned.

**Comment by sgaynetdinov** [comment]
I propose to create an organization "py-trello".
So that interested participants can work for "py-trello"
Also think over often updates in "PyPi"

**Comment by sgaynetdinov** [comment]
@jcchristian and @sarumont send invite to https://github.com/py-trello

**Comment by delucks** [comment]
@sarumont would you be open to performing another PyPI release? There have been several major bugfixes since the last one in late 2018.

**Comment by sarumont** [comment]
@delucks Published a new version to PyPi

**Comment by delucks** [comment]
Thank you @sarumont!

**Comment by sgaynetdinov** [comment]
@juanchristian close?
