### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by diegojromerolopez** [sarumont/py-trello#204]
What is the policy regarding Python 2 support? **master** has no Python 2 support currently.

**Comment by sgaynetdinov** [comment]
Hi, @diegojromerolopez 
> What is the policy regarding Python 2 support?
Should support Python2.7+

> master has no Python 2 support currently.
Can show that does not work ?

**Comment by diegojromerolopez** [comment]
Hello Sergei.

Python3 style constructors in several classes break Python 2.7 compatibility.

For example: https://github.com/sarumont/py-trello/blob/master/trello/checklist.py#L14

I have a Python2 version compatible in https://github.com/diegojromerolopez/py-trello/tree/python2-support

Should I make a PR with my branch?

**Comment by sgaynetdinov** [comment]
> Should I make a PR with my branch?
send Pull Request

**Comment by diegojromerolopez** [comment]
OK, done. Thank you.

I'm going to close this issue.
