### ISSUE TITLE
Trello __init__.py import urllib --> urllib.parse

### ISSUE THREAD

**Issue by JoshZastrow** [sarumont/py-trello#220]
Hi, it seems Trello package cannot be imported when using Python 3.5.

urllib package has been updated, now 'quote_plus' is in urllib.parse

>>> import trello
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\Anaconda3\envs\trello\lib\site-packages\trello\__init__.py", line 1, in <module>
    from urllib import quote_plus
    ImportError: cannot import name 'quote_plus'

This __init__.py file should be updated; line 1 changed to:

from urllib.parse import quote_plus

**Comment by bdamay** [comment]
Same here. Thanks for the workaround

**Comment by machinekoder** [comment]
I can confirm this.

**Comment by spyoungtech** [comment]
There's probably a confusion here and in #254 -- There is another [trello](https://pypi.org/project/py-trello/) project on PyPI (what you get when doing `pip install trello`). However, _this_ project, `py-trello` **is a completely different project!**

According to the git history of this project, that import never existed, so this issue must refer to the old unmaintained `trello` project.

**Comment by sarumont** [comment]
@spyoungtech Thanks for the clarification there. I'm closing this as not relevant, as the `quote_plus` import does not exist.
