### ISSUE TITLE
can't set attribute errror on tests scripts

### ISSUE THREAD

**Issue by angsm** [sarumont/py-trello#256]
Hi, I keep getting this error from the latest build in GITHUB from all the test scripts:

  File "build/bdist.linux-x86_64/egg/trello/card.py", line 191, in fetch
    self.labels = Label.from_json_list(self.board, json_obj['labels'])
AttributeError: can't set attribute

**Comment by AlexanderLill** [comment]
Same here, using OSX and python3.7.0

**Comment by sibson** [comment]
Confirmed, this fix solves the problem.  Would it be possible to have a pypi release to include this change?

**Comment by sarumont** [comment]
@sibson Pushed `0.13.0` up to pypi
