### ISSUE TITLE
fetching comments, no badges

### ISSUE THREAD

**Issue by angsm** [sarumont/py-trello#257]
Hi,

May I know what are badges? In the "fetch_comments" function in card.py, I can't seem to get any comments back as "(self.badges['comments'] > 0)" is not fulfilled.

**Comment by angsm** [comment]
I used force=True to bypass it. But I still want to know what badges are and how they can be added though.

**Comment by sarumont** [comment]
Should be fixed by the above PR. Thanks, @delucks!
