### ISSUE TITLE
can I move an individual card from one board to another board using py-trello?

### ISSUE THREAD

**Issue by mals14** [sarumont/py-trello#270]
I searched in the cards.py file and could not find a function that would help me achieve this. 

Would hate to have to resort to Trello API which I do not know yet how to systematically build the post URL. :(

I think this is what I effectively need to do. Would prefer to do so using py-trello. Thank you for your help.
```
From - https://developers.trello.com/v1.0/reference#cardsid-1

If you want to move a card across different boards, you should use the ID of the new board as well as ID of the target list:

PUT /1/cards/{id}/idBoard?value={new list ID}&idList={new list ID}
```

**Comment by sarumont** [comment]
@mals14 Glad you solved it! I'm closing this issue as it seems you have it figured out. Thanks for the link, too!
