### ISSUE TITLE
Create a new card

### ISSUE THREAD

**Issue by GNUGradyn** [sarumont/py-trello#276]
Looking thru the source code I couldn't find a function to create a card, how do you create a card?

**Comment by SkullTech** [comment]
I want to know this too. @sarumont Any pointer?

**Comment by SkullTech** [comment]
@GNUGradyn I found it! The `List` objects have an `add_card` method. [Here](https://github.com/sarumont/py-trello/blob/master/trello/trellolist.py#L90) is the source code.

**Comment by sarumont** [comment]
@SkullTech has it...`Cards` are children of `Lists`, so you have to create it from the `List` object.
