### ISSUE TITLE
Difficult to authenticate - any tips?

### ISSUE THREAD

**Issue by mbbroberg** [sarumont/py-trello#305]
Hey all, thanks for writing this helpful module. 

I was wondering if others have a more efficient way of retrieving the token and token secret when writing projects that use py-trello. My current instructions are somewhere between a spy novel and a scene from Momento. Here it is: 

## The right solution to authenticating

1. Go to https://trello.com/app-key/
2. Your API key is at the top
3. Your API secret is at the bottom (ignore the fact it's under the OAUTH section. That's misleading when it comes to usage)
4. Clone this repo https://github.com/sarumont/py-trello
5. Install the requirements: I use virtualenv so:
    1. cd py-trello
    2. virtualenv venv
    3. source venv/bin/activate
    4. pip install -r requirements.txt
6. Run the helper utility to get your token and token secret:
    - Add a `main` method to `trello/util.py` after the definition: 
    ```python
    if __name__ == "__main__":
        create_oath_token()
    ```
    - export TRELLO_API_KEY="YOUR KEY" && export TRELLO_API_SECRET="YOUR SECRET" && python trello/util.py
    - Follow the link provided which looks like https://trello.com/1/OAuthAuthorizeToken?oauth_token=baf9302393key280392zing&scope=read,write&expiration=30days&name=py-trello
    - Authorize
    - Go back to the command-line and respond to the prompt
        1. yes
        2. enter the pin provided on the Authorization page (Alternatively: the "pin" is an authentication Token you can generate on [this page](https://trello.com/app-key/))
 7. Copy your oauth_token and oauth_token_secret

You now have all the pieces to authenticate using the `trello.TrelloClient()` function.

## Question

Is there a better way? 

Thanks!

**Comment by mbbroberg** [comment]
Hey @sarumont, nudging this your way in case you have any tips. I'd love to write up or PR changes to make it easier. Thanks 👋

**Comment by sarumont** [comment]
@mbbroberg That sounds about right, given the API at the time I originally wrote this. It may be possible to use an OAuth token against the Trello API now (one would think...). In this case, a PR would be welcome to use that rather than the OAuth secrets. 

This would be a more modern approach to API authentication, however I have not personally been using `py-trello` or Trello's API at all recently.

**Comment by mbbroberg** [comment]
Thanks @sarumont. If I find a smarter way I'll PR It.
