### ISSUE TITLE
Inconsistent `card.label` typing

### ISSUE THREAD

**Issue by gastrodon** [sarumont/py-trello#330]
If a card has labels a list of `<Label>` is returned, but if it has none, `None` is returned. Why? It would seem preferable to me to return an empty list, since this
- doesn't break things that depend on a list (ie iterating a card's labels)
- better represents the actual labels on a card (an empty set of lables, which is different from nothing)

**Comment by sarumont** [comment]
Agreed, that should return an empty list for consistency.

**Comment by gastrodon** [comment]
I can submit a simple patch for this if you're accepting pulls

**Comment by gastrodon** [comment]
Hey @sarumont, do you have any intention to merge or review #331 related to this?

**Comment by sarumont** [comment]
Closed, as #331 was merged.
