### ISSUE TITLE
No timeouts makes apps that use this library to hang from time to time

### ISSUE THREAD

**Issue by PiotrCzapla** [sarumont/py-trello#337]
Hi, Thx for building the library. 
We are using it to automate some trello tasks, unfortunately when the board is big trello api tends to hang on ssl connection, since there is no timeouts the underlying .request hangs forever.

I would add a timeout parameter here:
https://github.com/sarumont/py-trello/blob/master/trello/trelloclient.py#L223-L226
and here https://github.com/sarumont/py-trello/blob/master/trello/trelloclient.py#L277

I'm not sure if you are maintaining this repo as the pull request are hanging for ages so for the time being I'm changing the http_service to something that adds timeouts, as follows:
```
class RequestsWithTimeouts:
    def __init__(self, timeout):
        self.timeout = timeout

    def _inject_timeout(self, kwargs):
        timeout = kwargs.get('timeout', self.timeout)
        kwargs['timeout'] = timeout
        return kwargs

    def request(self, *args, **kwargs):
        return requests.request(*args, **self._inject_timeout(kwargs))

    def post(self, *args, **kwargs):
        return requests.post(*args, **self._inject_timeout(kwargs))

trello_client = trello.TrelloClient(
            api_key=config.TRELLO_KEY, 
            api_secret=config.TRELLO_SECRET, 
            http_service=RequestsWithTimeouts(timeout=(60, 30)))
```

**Comment by sarumont** [comment]
@PiotrCzapla Hi - thanks for the suggestion. I'm still accepting pull requests and publishing releases, though I'm not doing any active development on the library anymore. Feel free to send over a PR, and I'll be happy to merge it!

**Comment by PiotrCzapla** [comment]
THank you, Although we are phasing out trello as it isn't handling well the traffic we have (4k cards per month). So I'm snowed under due to migration. If I find a minute I will write a PR and send over. I put that on my todo list so we can close this issue.
