### ISSUE TITLE
Integrate pending working pull requests

### ISSUE THREAD

**Issue by chaami** [sarumont/py-trello#362]
Hi @sarumont ,
First allow me to wish you a happy 2023 year and to thank you for all the work you have pushed on py-trello so far.

There have been a few interesting pull requests that have remained opened for a little while now.
A few of them are actually fixes of problem that we hit using the library...
Would you be kind enough to have a look at them so we can hope a release integrating them soon ?

Alternatively, are willing to completely unplug py-trello, in which case, shall we be looking for a maintainer to relieve you from the burden ?

Thanks again and kind regards.

**Comment by sarumont** [comment]
Thanks for the ping, @chaami. Work notifications have made my Github Notifications unusable for awhile. :)

Got all the pending PRs merged and published `0.19.0` with all those changes.
