### ISSUE TITLE
'Member' Object has no 'Email'

### ISSUE THREAD

**Issue by Averiandith** [sarumont/py-trello#363]
https://github.com/sarumont/py-trello/blob/c711809a076aee3fc04784e26e6b0b9688229ebd/trello/member.py#L27

Kindly note that 'Member' object does not have 'email' as an attribute.

**Comment by ScottG489** [comment]
I think this will be the case if you didn't grant "account" level permissions to the credentials you're using.

**Comment by Averiandith** [comment]
I see, thanks @ScottG489.
