### ISSUE TITLE
Probable Repo Abandonment

### ISSUE THREAD

**Issue by Kab00mKap0w** [sarumont/py-trello#376]
Due to Trello API changes, the py-trello package on the main branch has been inoperable now for almost 6 weeks. Approximately 20 users have posted their concerns and discoveries, and the vocal minority often represent a greater number.

There are two pending PRs that address fixes. People have attempted to reach the original maintainer @sarumont without success. His account continues to show activity, so it's likely the messages were received.

I'm opening this issue to discuss options for ensuring the continued support of the code. That could mean:

- sarumont resumes maintenance, optimally with support of other admins
- sarumont passes on the repo to new admins
- A fork becomes the new official repo
- Other options as proposed

I don't have experience with this, but py-trello is a quality package that deserves to be kept alive.

**Comment by Konano** [comment]
For personal needs, I have forked this repository and merged two pending PRs into the new repository.
https://github.com/Konano/py-trello-api

As a temporary solution, I have also uploaded the new package to Pypi. You can download the fixed py-trello with this command:
`pip install py-trello-api==0.20.0`

I hope this helps someone in need.

**Comment by sarumont** [comment]
Hi all. I have merged the two linked PRs and will publish a new version to PyPi shortly. Apologies for the neglect, but I have been fighting work Github notifications and lost track of any personal notifications in the process. :)

**Comment by sarumont** [comment]
And released ✔️

**Comment by Kab00mKap0w** [comment]
Perhaps the project can now be upgraded from "Likely Abandoned" to "Neglected." It was 8 weeks before we saw the critical PRs merged, but that release still requires end users to fix a bug ([#377](https://github.com/sarumont/py-trello/issues/377)). It's been one week since that issue was reported. Although a trivial fix, it remains.

@sarumont please add other maintainers to the project. It will give you relief while offering hope to others that this code base can again become reliably maintained.

**Comment by Ortega-Dan** [comment]
@sarumont Please merge #379 which fixes the issue. And release :pray:

**Comment by ogarcia** [comment]
I agree with @Kab00mKap0w. @sarumont you should open a process to choose some collaborators in the project so they can help you with the maintenance.

Personally I can lend a hand and I imagine if you ask there will be more people willing to do it.

**Comment by sarumont** [comment]
Released `v0.20.1`, and I will work to get this repo into a more manageable state (CI, publication, and adding maintainers). Thank you for your patience!

**Comment by Kab00mKap0w** [comment]
I'm closing this issue since Sarumont fixed the critical bug and the bad merge. I had considered starting a new issue "Add maintainers to the project" to follow up on what he said on Jun 11, but I don't want to be pushy. 

There have been no additional issues opened for bugs. That both removes the pressure for Sarumont to add maintainers while giving him the time to do so to his satisfaction. I hope the latter case works out for the best. @sarumont thank you for creating this great package. Please include me in the pool of people who are offering you support however you need it.
