### ISSUE TITLE
Syntax error in version 0.20.0

### ISSUE THREAD

**Issue by OrBin** [sarumont/py-trello#377]
```
  File "/usr/local/lib/python3.10/site-packages/trello/__init__.py", line 11, in <module>
    from trello.trelloclient import *
  File "/usr/local/lib/python3.10/site-packages/trello/trelloclient.py", line 217
    <<<<<<< jsadowski/feature/http-user-agent
    ^^
SyntaxError: invalid syntax
```

Seems like an unresolved merge conflict: https://github.com/sarumont/py-trello/pull/375/files#diff-089a18eb2efe544d0de47b823159af273a65c73284066e4b4b9e0e51efbf0a34R217-R224

**Comment by bitclick** [comment]
yes this is a quick fix. please do it
for now i just changed the affected file directly
