### ISSUE TITLE
AttributeError: 'Http' object has no attribute 'fetch_json' when calling list_cards()

### ISSUE THREAD

**Issue by racemidev** [sarumont/py-trello#63]
When I run an example list test40_add_card() in test_trello.py, I have no trouble calling add_card() on a list object, however, if I get a card in a different way, then it looks like the client attribute isn't initialized correctly.  My usage is a bit convoluted, namely because I don't see a way to fetch a card by its ID or its name, but:
b = trello.get_board('myboard')
for card in b.get_cards(myfilter):
    if card == desired_card:
        l = trello.get_list(card.idList)
        l.add_card(cardname, 'delete me')

gives me the AttributeError.  The documentation is a little sparse but am I expected to initialize objects in a certain order or ... ?

Ultimately I'm trying to implement a List.copy_card() method to create a new card from a template in a given list.

**Comment by josephmisiti** [comment]
+1

**Comment by sarumont** [comment]
@racemidev: do you still see this? I attempted to duplicate it in a unit test, but it doesn't look to be an issue anymore:

```
def test45_issue63(self):
        board = self._trello.get_board(self._board.id)
        for card in board.all_cards():
            print "Card %s (%s)" % (card.name, card.id, )
            if card.id == '5596d28e7a86ffca44ff94e8':
                l = board.get_list(card.idList)
                break
        l.add_card("some card", "test")
```

"some card" is properly added to the list. Side note: `trello.get_list` does not exist - Accessing a list can (currently) only be done via a `Board`

**Comment by josephmisiti** [comment]
I am not longer see this issue. The issue seemed to be that the latest version in pip did not match the version at HEAD

**Comment by sarumont** [comment]
Cool - I'll close it out. Thanks!
