### ISSUE TITLE
KeyError in Member due to latest pull request

### ISSUE THREAD

**Issue by maximebf** [sarumont/py-trello#80]
The latest pull request introduced a bug which makes the library unusable for me:
```
File "/....../trello/__init__.py", line 917, in fetch
    self.commentCard = json_obj['commentCard']
KeyError: 'commentCard'
```

**Comment by nMustaki** [comment]
If you need it working right now, you can correct the api call to this : 
```python
json_obj = self.client.fetch_json(
            '/members/' + self.id,
            query_params={'badges': False, 'actions': ['commentCard']})
```
or you can remove line 917 if you don't need it

**Comment by nMustaki** [comment]
By the way, I am in the lazy camp and think removing line 917 is the right choice
