### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by WoLpH** [sarumont/py-trello#90]
It would be great if the version on Pypi would be updated, it's a tad out of date :)

This should do the trick:
```
python setup.py sdist upload
```

**Comment by sarumont** [comment]
I'll try to get this done this weekend. I need to import all my PGP keys onto my new laptop anyway.

**Comment by WoLpH** [comment]
Awesome, that would be brilliant :)

The current git version still has some bugs but it works better than the old one for me

**Comment by markmc** [comment]
Anything I can do to help here?

I'll get this packaged and included in Fedora once there's a release

**Comment by sarumont** [comment]
Mark,

Aside from my day job, nope. :)

I'll push to get it built today - I have gotten as far as getting my PGP
keys loaded onto the new laptop, so it should be pretty quick to push.

Cheers!

**Comment by sarumont** [comment]
Here we go:

https://pypi.python.org/pypi/py-trello/0.3.1

I'm in a better place to push these in the future, so I'll make it a more frequent event. :) Cheers!

**Comment by markmc** [comment]
Awesome, thanks @sarumont !
