### ISSUE TITLE
dateutil ImportError

### ISSUE THREAD

**Issue by raptortech-js** [sarumont/py-trello#95]
When I try to download and run this code, I get an ImportError because it can't find the dateutil module. When I download and run the source for the 0.1.6 release, everything works fine.

**Comment by npike** [comment]
It looks like the dateutil module is this:  https://labix.org/python-dateutil

If you are loading this module as source (and not installing via pip) you should be able to download the dateutil module and append its path to sys.path.

ex:

    import sys
    sys.path.append("python-dateutil-1.5")

**Comment by sarumont** [comment]
@raptortech-js Are you still seeing this issue? If you are using `pip` to install, I just updated the release, so  `python-dateutil` should get installed properly.

**Comment by raptortech-js** [comment]
Looks like that fixed it, thank you
